### ISSUE TITLE
time in strict mode or not?

### ISSUE THREAD

**Issue by dpshelio** [dmlabdmlab/QueryHEK#1]
I've made the following query:

``` yaml
Start Date : 2011-08-09
Start Time : 07-18-00
End Date : 2011-08-09
End Time : 07-30-00
Event Type : fl
Spatial Region : helioprojective, -5000,5000,-5000,5000
```

and I've got 4 events with the following start and end times:

| start time | end time |
| --- | --- |
| 2011-08-09T07:19:00 | 2011-08-09T07:27:00 |
| 2011-08-09T07:19:00 | 2011-08-09T07:27:00 |
| 2011-08-09T07:22:38 | 2011-08-09T08:32:02 |
| 2011-08-09T07:22:44 | 2011-08-09T07:28:56 |

which it doesn't follow the strict mode as if querying [HEK](https://www.lmsal.com/hek/her?cosec=2&&cmd=search&temporalmode=strict&type=column&event_type=fl&event_region=all&event_coordsys=helioprojective&x1=-5000&x2=5000&y1=-5000&y2=5000&result_limit=120&event_starttime=2011-08-09T07:18:00&event_endtime=2011-08-09T07:30:00&return=event_starttime,event_endtime), where the third result does not appear. And [if I don't use the strict mode](https://www.lmsal.com/hek/her?cosec=2&&cmd=search&type=column&event_type=fl&event_region=all&event_coordsys=helioprojective&x1=-5000&x2=5000&y1=-5000&y2=5000&result_limit=120&event_starttime=2011-08-09T07:18:00&event_endtime=2011-08-09T07:30:00&return=event_starttime,event_endtime) hek returns 11 events.

So, how QueryHEK is handling the time ranges?
